### ISSUE TITLE
License badge is broken

### ISSUE THREAD

**Issue by krugerk** [beeminder/BeeSwift#205]
We were using a status badge for the license using https://github.com/badges/shields. Commit 31bfceaeaa126adc9290b45afb17fc08832c8279 broke the license detection used and now the license badge shows up as 
<img width="293" alt="Bildschirmfoto 2020-09-27 um 23 14 47" src="https://user-images.githubusercontent.com/4656811/94375988-e010b900-0117-11eb-9a8c-09179f1262cc.png">

This could very well be a feature though and indicate that licenses are not what they appear to be.  🤔

# Expected
 1 - It is clear(ly documented) which components are available under which license.
 2 - The license status badge correctly displays the matching license.

**Comment by andrewpbrett** [comment]
I'd say we should revert that commit and have the License be standard and add the caveats about the logo and name elsewhere, maybe in the Readme. I think it's usually understood that the license refers specifically to the code itself and not associated marks etc. @dreeves

**Comment by dreeves** [comment]
Sounds fine to me! I don't know that I'd care about the license badge thing but also don't care where we clarify what the license applies to. So, yeah, Andy's in charge!

PS: I see CodeCombat has the same badge problem:

https://img.shields.io/github/license/codecombat/codecombat

PPS: I see that that badge only appears because we've explicitly put it in the README. Maybe we just... don't do that? Anyone who cares about the license can just click the "view license" link in the sidebar, right?

**Comment by krugerk** [comment]
addressed in #566
