### ISSUE TITLE
Delta text does not match due by table

### ISSUE THREAD

**Issue by andrewpbrett** [beeminder/BeeSwift#229]
```[tasklist]
### Desiderata
- [ ] Ideally replace that "delta text" with a due-by table (so maybe #209 makes this moot?)
```

Andy's original comment: Not positive this is a bug, or that it's a bug in iOS as opposed to something in the API/Beebrain.

App:
<img width="228" alt="Screen Shot 2020-11-20 at 6 02 27 PM" src="https://user-images.githubusercontent.com/35588/99864844-8eeed580-2b5a-11eb-91f3-ba7725a330d7.png">

Website:
<img width="174" alt="Screen Shot 2020-11-20 at 6 02 44 PM" src="https://user-images.githubusercontent.com/35588/99864852-9a420100-2b5a-11eb-8ba2-d1cdcfc06b7b.png">

## Cognata

* #209 

_**Verbata**: due-by table, delta from bright red line, beebrain adjacent,_

**Comment by krugerk** [comment]
#209 replacing the delta text with the due by table

**Comment by krugerk** [comment]
Could also have been that the stats were out of date as displayed in the goal on the website. Sometimes changes are made to the goal (data added/removed/scaled) and the stats are not updated and the notice that they are out-of-date is not displayed.  Refreshing the page

**Comment by krugerk** [comment]
Another user reported the same: data displayed in app as delta text (colored text under the graph when viewing a goal) did not match the data presented in the stats section on the website, which shows data from the 'due by' table.

App showed delta text:
![image](https://user-images.githubusercontent.com/4656811/100363237-bcc19780-2ffc-11eb-9baa-64d6a694a2d5.jpeg)

And website showed due by:
![image](https://user-images.githubusercontent.com/4656811/100363290-cfd46780-2ffc-11eb-8e31-1a17800a7829.jpeg)


In this case we would expect the delta text to be empty (and thus no colored text just below the graph in the app) because the goal's current value is sufficient to cover the amount due in seven days.

**Comment by krugerk** [comment]
It could be a separate ticket - `JSONGoal.attributedDeltaText` turns three checkmarks into some number


delta_text:
"✔ ✔ ✔"

attributedDeltaText:
+ 0.01{
    NSColor = "UIExtendedSRGBColorSpace 0.317647 0.639216 0.317647 1";
}


From the looks of it,
https://github.com/beeminder/BeeSwift/blob/e4700533c781e4e25352fbe53cb9064faa6d97ec/BeeSwift/JSONGoal.swift#L245
the three checkmarks above are replaced by `JSONGoal.safebump` - `JSONGoal.curval`, rounded to two decimal places.

**Comment by theospears** [comment]
Delta text has been removed
