### ISSUE TITLE
Apple Health integration: Number of workouts

### ISSUE THREAD

**Issue by phdoerfler** [beeminder/BeeSwift#254]
As a user I want to beemind the number of workouts done. Workouts that appear in Apple Health like so:
<img width="375" alt="image" src="https://user-images.githubusercontent.com/163428/106357794-8fe57580-6308-11eb-8c2f-153e114c37ab.png">

**Comment by phdoerfler** [comment]
I changed my mind, minutes exercised should suffice for my use case.

**Comment by krugerk** [comment]
Hello and thanks for the request. I see you closed it right away commenting that you would find another approach. You might not need it anymore and you are right, there are ways to obtain the data. 
Nonetheless, this could be something the app handles and, at the very least, documenting the types of data that can be extracted from the HealthKit metrics would provide us with a documented status quo (#75).
I marked this one as "not now" via the ZzZ label since you closed it and mentioned Ticket #75 so that this one appears on that one, as a reminder.

**Comment by krugerk** [comment]
Furthermore, this appears to be a duplicate of #74.
