### ISSUE TITLE
Create HealthKit goal in app

### ISSUE THREAD

**Issue by krugerk** [beeminder/BeeSwift#258]
Recently the webapp's workflow for creating a new goal sourced via Apple Health was updated to point to the helpdocs explaining the required steps. 
Many (if not all) of the other integrations can be created via 'wizard' via the webapp. Apple Health is an exception in that one would need to create the goal elsewhere (via the website or API) and then configure it in the Beeminder iOS app on an iOS device.

The iOS app should support creating goals, in particular ones integrated with Apple Health. 
Maybe the flow doing so in app can be somewhat different, targeting goal creation for the various metrics: time in bed, steps, and so on.

**Comment by dreeves** [comment]
Thanks for suggesting this! I've marked it "snoozed" since it's not exactly on the roadmap at this point. Philosophically, we're intentionally keeping the smartphone apps as strictly auxiliary -- dashboard, reminders, data entry -- with everything else, like creating goals, done on the website.

The UI for creating an Apple Health goal is pretty lousy, creating a manual goal first and all, but I think the first place to improve that is the website before adding new functionality to BeemiOS.
