### ISSUE TITLE
Be smarter about warning me to unlock my phone

### ISSUE THREAD

**Issue by dreeves** [beeminder/BeeSwift#44]
User Kirsty says:

> It seems to remind me to unlock my phone to sync my health data with Beeminder every day no matter that I unlock my phone many many many times each day.  I don't know why this reminder is necessary but it either needs something other than it says or it's pointless.

**Comment by dreeves** [comment]
Kirsty adds:

> the notification popped up this morning while I was using my phone so "unlock your phone to.." seemed very weird for it to be saying!

**Comment by andrewpbrett** [comment]
I think we just need to remove this notification entirely.

**Comment by krugerk** [comment]
I myself would have created a new ticket and referenced this one in the description.
This ticket was 'be smarter about the unlock' notification, especially that it not be shown while the user's device was not locked while the user was navigating in the app.
This was implemented.

The new task seems to be instead to remove the notification and its setting entirely.

To facilitate tracking changes, relevant for release notes, I would have made that its own task/ticket.

**Comment by andrewpbrett** [comment]
I could see why a separate ticket might be better, but the behavior described by the user is that the notification arrives even though her phone has been unlocked during the day. Since that behavior is still happening, I think it's the same ticket. I shouldn't have closed the issue in the first place, that's my fault.

**Comment by krugerk** [comment]
No worries. Perhaps you can shed some light into why the notification is needed (was needed).

**Comment by andrewpbrett** [comment]
Since Apple Health data isn't available when the phone is unlocked, if someone, for example, had a steps goal that needed steps before midnight and they went for a walk from 23:30 - 00:15 in order to get the steps in, but didn't unlock the phone while they were walking, there would be no way for Beeminder (or any other app) to update the step total before midnight. 

However, even if the phone is unlocked, there's not a guarantee that the health goal will be synced. Since the notification is 1) misleading (it implies that opening your phone is all that it takes to sync the data) and 2) not working as intended (it arrives even if the phone has been unlocked recently) I think we need to remove it entirely until we can rethink it. I don't think it's a priority to reimplement, however.

**Comment by krugerk** [comment]
Yeah those original motivations are good to know.

**Comment by mauricioralcala** [comment]
Hello, this notification is driving me insane. The only notifications I have on in my phone are Beeminder (this ensures I take care of my commitments and focus better) and Phone app. But I get this multiple times per day, despite unlocking my phone many times. Could we get the option to turn this off?

**Comment by krugerk** [comment]
> Hello, this notification is driving me crazy. The only notifications I have on in my phone are Beeminder (this ensures I take care of my commitments and focus better) and Phone app. But I get this multiple times per day, despite unlocking my phone many times. Could we get the option to turn this off?

Feel free to disable them altogether on your device. You can find the option in the app under settings / health app integration. "Sync Health data reminders"

**Comment by mauricioralcala** [comment]
> > Hello, this notification is driving me crazy. The only notifications I have on in my phone are Beeminder (this ensures I take care of my commitments and focus better) and Phone app. But I get this multiple times per day, despite unlocking my phone many times. Could we get the option to turn this off?
> 
> Feel free to disable them altogether on your device. You can find the option in the app under settings / health app integration. "Sync Health data reminders"

I can't because it is helpful for one of my goals to know when I have a Beemergency. Those notifications are useful.

**Comment by andrewpbrett** [comment]
Hi @mauricioralcala - I've removed the notifications in version 5.9. Once it's tested I'll submit it to the App Store and it should appear within the next few days.

**Comment by andrewpbrett** [comment]
If you'd like to preview the new version, @mauricioralcala, you can download it via TestFlight: https://testflight.apple.com/join/U26BrdwB
