### ISSUE TITLE
Timer could alert user to destructive operations

### ISSUE THREAD

**Issue by krugerk** [beeminder/BeeSwift#61]
[This is too sprawling of a gissue. Let's start with #5 and add new things as they come up.]

Beeminder iOS App BeeSwift 5.6.4

The Timer consists of the countup, a button for start/stop, a button for adding a datapoint, as well as buttons for exiting the timer and resetting the timer.

#### Exit Button
As is, Exit leaves the Timer having not added a datapoint. The user is also not prompted to confirm leaving the timer, which might be handy with data in the timer. 
#### Reset Button
As is, Reset resets the timer having not added a datapoint. The user is also not prompted to confirm. 

#### Confirmation of destructive operation
I mention destructive operations in the title since we lose the timer data in these two cases. This may very well be what the user intends and I think it is common practice to ask for confirmation (especially when not providing an undo) before similar tossing data. (As an example, deleting a datapoint within the app does obtain confirmation.)

#### Misc
While on the topic of the timer, it might be helpful to have a reference to the goal appear on the screen when viewing the timer. Another tweak might be for Start to be replaced with Resume/Continue or similar as long as the timer has already been started (user tapped Start, waited say five seconds, tapped Stop. Start is shown which does start the timer again - notice "start again" aka resume. Alternatively from the days of tape decks and CD players, the button was usually play/pause together with stop being on its own.)

#### Not too long, did read
Thus the proposal is as follows:
 - show the goal slug on the timer
 - ask for confirmation when exiting the timer as long as there is an active timer
 - ask for confirmation when resetting the timer as long as there is an active timer
 - the start stop button text displays any of Start (when neither a timer nor ticking), Stop (when there is a timer and ticking), and Continue/Resume or similar (when there is a timer not ticking - has been paused/stopped)
 - (for that matter, the reset button can be enabled based on having data to be reset)

**Comment by dreeves** [comment]
I'm not very clueful about the Beeminder iOS app so I don't have much useful to say about this other than it sounds smart!

But one possibly useful thing to mention is that Beedroid does this really well and may be worth emulating. For example, Beedroid never loses your timer data because it permanently remembers that you started a timer and when, so it doesn't matter if you close the app -- when you come back the timer will be counting up as if nothing happened.

I suspect that's the most important thing. Beedroid doesn't actually ask for any confirmation to reset the timer without submitting it and I'm not sure it should.

(Thanks for helping think all this through!)

**Comment by 6Vmf2y48AaGbfTD2-vfDsr759VA49m-uePFkE** [comment]
If we have a timer running and tap Exit, perhaps even accidentally, the Timer is closed and the data (the running timer) destroyed.

I can agree that the exit exits; I was just expecting a "btw you are about to lose the data from the timer you had running the last 45minutes".

As for the other matter, I think you may be referring to #5, which is its own ticket/issue.
