### ISSUE TITLE
allow disabling sentry

### ISSUE THREAD

**Issue by krugerk** [beeminder/BeeSwift#77]
The app provides the options for authenticating via username(email)/password as well as through facebook and twitter. 

For one only using email (registered at beeminder)/password to log in, there is no need to present or even load facebook and twitter.

Similarly, I see Sentry (crash tracking) in the Podfile. We could offer an option to disable this as well (not just not sending crash reports but preventing the resource from being loaded).

GDPR

**Comment by andrewpbrett** [comment]
I'm all for reducing the tracker/third party code footprint of the app, but I don't know that this is worth the effort. We'd still have to ship the app with Facebook and Twitter libraries in order to support logging in with them. I suppose we could do a "lazy load" of the buttons only if the user says they need to use them, but then you're asking them to press a button in order to press a button. Before they've signed in, we wouldn't be able to tell if the user only used email vs Facebook and twitter, because, well, they haven't signed in yet!

For Sentry, I chose it because it's itself open source and the least icky, tracking wise, that I could find. If we want to put a toggle in settings for people to opt out of crash reports, though, I'd be fine with that, if it doesn't introduce a lot of mess in the code to always be checking for whether the user has opted out.

**Comment by krugerk** [comment]
The idea would be that the options are there in app settings. Each of those items could be toggled on/off. Some might require a force close and new start of the app before taking effect.

Or perhaps the other way around would work well too: at first app start, ask if the person wishes to use any of them, enabling those that are selected. If needed restart the app. 


I am not sure merely not initializing the library is enough to prevent data from leaking to FB when deactivated. 
There was that issue in May with [several apps crashing on account of the embedded Facebook sdk crashing.](https://github.com/facebook/facebook-ios-sdk/issues/1374)

**Comment by andrewpbrett** [comment]
Looks like it's happening again with Facebook, though I don't see any crashes for us and I can open the app just fine: https://github.com/facebook/facebook-ios-sdk/issues/1427

**Comment by Daniel15** [comment]
@andrewpbrett That crash only affected old versions of the SDK.

**Comment by krugerk** [comment]
> @andrewpbrett That crash only affected old versions of the SDK. 

Older than 4.11.0 from May 2016? That is the version we are using.

**Comment by andrewpbrett** [comment]
Facebook and Twitter's SDKs are now removed, so that just leaves the option to disable Sentry, if we want to do that.

**Comment by krugerk** [comment]
for reference, 3rd party logins were removed in #107

**Comment by krugerk** [comment]
For whatever reason I do not not sentry nearly as much as twitter and facebook. I suppose those for people logging in with either, ...

**Comment by krugerk** [comment]
![enable analytics](https://user-images.githubusercontent.com/4656811/100528306-bdfceb00-31db-11eb-801c-450a06fbf4d7.png)

The official beeminder app for android supports disabling analytics. As reported in the copy and upon disabling analytics, the user is informed that the setting only takes effect upon the next start of the app.
