### ISSUE TITLE
Offline support

### ISSUE THREAD

**Issue by krugerk** [beeminder/BeeSwift#87]
Offer (better) offline support
... 

The user has an account, has logged in, data for user and goals has been downloaded.

At this point I would anticipate the app would offer a basic amount of offline functionality:

Viewing goals
Viewing datapoints of goals
Viewing graphs 
Filtering goals 
(Re-)Sorting goals 
Viewing notification settings
Viewing health kit integration settings 

Actually most of the above already work, except for the graphs and notifications, as long as the app remains in memory. After a force-quit none of them are available upon starting the app anew.
Here too it would be nice to at least be able to view the data as it was the last time it was fetched.

I realize supporting adding data during offline mode is a different can of worms and am currently not proposing that. There are though times when adding data might be convenient while offline.

(Attempting to sign in while offline shows ‘invalid credentials’ instead of the ‘appear to be offline’ message.)

**Comment by adamwolf** [comment]
A key usability insight here is that notifications happen when you are
online, and if you are offline and expect the absence of notifications
indicates you are OK, you're gonna have a bad time.

This is not saying that I think offline mode is a bad idea, but I would be
hesitant about any proposals that improve offline use without covering this
user expectation.

**Comment by krugerk** [comment]
I mostly would not mind being able to browse through the app like normal while offline, but you are right. Push notifications are server generated and not app generated and would not be delivered to the device via Apple's Push Notification Service while offline.

**Comment by andrewpbrett** [comment]
I'll second what @adamwolf said, and add that the difference in how notifications are handled is probably the largest difference between how the Android and iOS apps operate. I believe we want to move more in the direction of what iOS does, ie rely on the server for notifications instead of the app scheduling them locally. 

For the graphs, though, it would be nice to have them persist locally, as long as we're making it really clear to the user that they're potentially out of date. 

Separately, for issues like this that we're not actively prioritizing, I think (but I'm not positive!) that the best status for them is closed. The discussion is still good to capture here and I like that it's searchable. If people think it'd be better to keep them open but with a different label I'd be open to being convinced. But I'll close this one for now.

**Comment by adamwolf** [comment]
If I comment, does it autoreopen?  It so, I'm sorry!

On Android, we are moving to having notifications generated on the server and being sent down.

We will still have lots of offline stuff in Beedroid, so I am thinking about how to fix up this UX snag.
